name: Deploy

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Copy repository contents via scp
              uses: appleboy/scp-action@master
              with:
<<<<<<< HEAD
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  strip_components: true
                  source: 'admin,assets,index.html'
                  target: '/root/public/callmeatnight.com/'
=======
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}                 
                port: ${{ secrets.PORT }}
                source: '.'
                target: '/root/public/callmeatnight.com2/'
>>>>>>> 285764b (Updates deploy target)
