name: Deploy

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Copy repository contents via scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  source: '.'
                  target: '/root/public/callmeatnight.com/'
